export default [
  {
    name: 'Sir Ahsan ',
    msg: 'Hey, how’s life going.',
    isSeen: true,
    time: '9:27 AM',
    id: 0,
    distance: ' 10 miles away',
    age: 22,
    dp: require('../../Assets/Images/no-profile.jpg'),
    address: ` are You there`,
    discription: 'Feminist. Cats. Other stuff that’s mildly interesting',
    isLike: false,
  },
  {
    name: 'Sir Shahid',
    id: 1,
    distance: ' 10 miles away',
    age: 25,
    dp: require('../../Assets/Images/no-profile.jpg'),
    address: ` hello everyone i'm new here`,
    discription: 'Feminist. Cats. Other stuff that’s mildly interesting',
    isLike: false,
    msg: 'Hey,',
    isSeen: false,
    time: '9:27 AM',
    isActive: true,
  },
  {
    name: 'WAQAR',
    id: 2,
    distance: ' 10 miles away',
    age: 36,
    dp: require('../../Assets/Images/no-profile.jpg'),
    address: ` hello everyone i'm new here`,
    discription: 'Feminist. Cats. Other stuff that’s mildly interesting',
    isLike: true,
    msg: 'Hey, how are you.',
    isSeen: true,
    time: '9:27 AM',
    isActive: true,
  },
  {
    name: 'Muzammil ',
    id: 3,
    distance: ' 10 miles away',
    age: 35,
    dp: require('../../Assets/Images/no-profile.jpg'),
    address: ` hello everyone i'm new here`,
    discription: 'Feminist. Cats. Other stuff that’s mildly interesting',
    isLike: false,
    msg: 'Hey, how’s life going.',
    isSeen: false,
    time: '9:27 AM',
    isActive: true,
  },
  {
    name: 'mudassir ',
    id: 4,
    distance: ' 10 miles away',
    age: 32,
    dp: require('../../Assets/Images/no-profile.jpg'),
    address: ` hello everyone i'm new here`,
    discription: 'Feminist. Cats. Other stuff that’s mildly interesting',
    isLike: true,
    msg: 'Hey, how’s life going.',
    isSeen: true,
    time: '9:27 AM',
    isActive: true,
  },
  {
    name: 'Shafique',
    id: 5,
    distance: ' 10 miles away',
    age: 40,
    dp: require('../../Assets/Images/no-profile.jpg'),
    address: ` hello everyone i'm new here`,
    discription: 'Feminist. Cats. Other stuff that’s mildly interesting',
    isLike: false,
    msg: 'Hey, how’s life going.',
    isSeen: true,
    time: '9:27 AM',
    isActive: true,
  },
  {
    name: 'HR Bilal ',
    id: 6,
    distance: ' 10 miles away',
    age: 28,
    dp: require('../../Assets/Images/no-profile.jpg'),
    address: ` hello everyone i'm new here`,
    discription: 'Feminist. Cats. Other stuff that’s mildly interesting',
    isLike: false,
    msg: 'Hey, how’s life going.',
    isSeen: true,
    time: '9:27 AM',
    isActive: true,
  },
  {
    name: ' mam Noor',
    id: 7,
    distance: ' 10 miles away',
    age: 30,
    dp: require('../../Assets/Images/no-profile.jpg'),
    address: ` hello everyone i'm new here`,
    discription: 'Feminist. Cats. Other stuff that’s mildly interesting',
    isLike: false,
    msg: 'Hey, how’s life going.',
    isSeen: true,
    time: '9:27 AM',
    isActive: false,
  },
  {
    name: 'mujtaba',
    id: 8,
    distance: ' 10 miles away',
    age: 30,
    dp: require('../../Assets/Images/no-profile.jpg'),
    address: ` hello everyone i'm new here`,
    discription: 'Feminist. Cats. Other stuff that’s mildly interesting',
    isLike: false,
    msg: 'Hey, how’s life going.',
    isSeen: true,
    time: '9:27 AM',
    isActive: false,
  },
  {
    name: 'ghayoor',
    id: 9,
    distance: ' 10 miles away',
    age: 30,
    dp: require('../../Assets/Images/no-profile.jpg'),
    address: ` hello everyone i'm new here`,
    discription: 'Feminist. Cats. Other stuff that’s mildly interesting',
    isLike: false,
    msg: 'Hey, how’s life going.',
    isSeen: true,
    time: '9:27 AM',
    isActive: false,
  },
  {
    name: 'faisal',
    id: 9,
    distance: ' 10 miles away',
    age: 30,
    dp: require('../../Assets/Images/no-profile.jpg'),
    address: ` hello everyone i'm new here`,
    discription: 'Feminist. Cats. Other stuff that’s mildly interesting',
    isLike: false,
    msg: 'Hey, how’s life going.',
    isSeen: true,
    time: '9:27 AM',
    isActive: false,
  },
  {
    name: 'ahsan',
    id: 9,
    distance: ' 10 miles away',
    age: 30,
    dp: require('../../Assets/Images/no-profile.jpg'),
    address: ` hello everyone i'm new here`,
    discription: 'Feminist. Cats. Other stuff that’s mildly interesting',
    isLike: false,
    msg: 'Hey, how’s life going.',
    isSeen: true,
    time: '9:27 AM',
    isActive: false,
  },
  {
    name: 'ali',
    id: 9,
    distance: ' 10 miles away',
    age: 30,
    dp: require('../../Assets/Images/no-profile.jpg'),
    address: ` hello everyone i'm new here`,
    discription: 'Feminist. Cats. Other stuff that’s mildly interesting',
    isLike: false,
    msg: 'Hey, how’s life going.',
    isSeen: true,
    time: '9:27 AM',
    isActive: false,
  },
];
