import {View, StyleSheet, Text} from 'react-native';
import {hp, wp} from '../../Global/Styles/Scalling';
import {fontFamily, fontSize} from '../../Global/Styles/Fonts';
import {
  gray,
  darkGray,
  white,
  whiteGray,
  theme2,
  theme,
  black,
  whiteGrayTwo,
} from '../../Global/Styles/Theme';
const styles = StyleSheet.create({
  showCaseContainer: {
    width: wp(100),
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: hp(2),
    marginBottom: hp(3.67),
    // borderColor: white,
    // borderWidth: 1,
  },
  titleContainer: {
    width: wp(100),
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp(1),
    paddingLeft: wp(4.8),
    paddingRight: wp(4.8),
  },
  itemContainer: {
    paddingLeft: wp(4.8),
    paddingRight: wp(4.8),
    width: wp(100),
    marginTop: hp(2),
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },

  item: {
    width: wp(16),
    height: wp(16),
    borderRadius: wp(8),
    backgroundColor: theme2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontFamily: fontFamily.UbuntuRegular,
    fontSize: 20,
    lineHeight: 23,
    color: white,
  },
  seeAll: {
    fontFamily: fontFamily.UbuntuRegular,
    textDecorationLine: 'underline',
    fontSize: 14,
    lineHeight: 21,
    color: '#818181',
  },

  itemName: {
    marginTop: hp(2),
    fontFamily: fontFamily.UbuntuRegular,
    fontSize: 14,
    lineHeight: 16,
  },
  contentContainer: {
    width: wp(42.93),
    height: hp(33),
    backgroundColor: theme2,
    marginTop: hp(1.6),
    borderRadius: 10,
    marginBottom: hp(2),
    // borderColor: white,
    // borderWidth: 1,
  },
  image: {
    width: wp(42.93),
    height: hp(12.68),
    resizeMode: 'stretch',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  likeButton: {
    position: 'absolute',
    zIndex: 100,
    left: wp(36),
    top: hp(1),
  },
  infoContainer: {
    // borderColor: white,
    // borderWidth: 1,
    // marginBottom: hp(1),
    justifyContent: 'space-evenly',
    // marginTop: hp(1),
  },
  rattingContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: hp(1.5),
    // borderColor: white,
    // borderWidth: 1,
  },
  ratting: {
    backgroundColor: theme,
    width: wp(16.25),
    height: hp(2.7),
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    borderRadius: 10,
  },
  ratingValue: {
    fontFamily: fontFamily.UbuntuRegular,
    fontSize: 14,
    lineHeight: 16,
    color: white,
  },
  itemLabel: {
    fontFamily: fontFamily.UbuntuRegular,
    fontSize: 18,
    lineHeight: 21,
    color: white,
  },
  priceContainer: {
    marginTop: hp(1.37),
    justifyContent: 'space-evenly',
    flexDirection: 'row',
    marginHorizontal: wp(3),
    // borderColor: white,
    // borderWidth: 1,
  },
  priceLabel: {
    fontFamily: fontFamily.UbuntuRegular,
    fontSize: 14,
    lineHeight: 16,
    color: '#818181',
    paddingHorizontal: hp(1),
  },
  timerContainer: {
    justifyContent: 'space-evenly',
    flexDirection: 'row',
    marginTop: hp(2),
    alignItems: 'center',
    // borderColor: white,
    // borderWidth: 1,
  },
  timeLabel: {
    textAlignVertical: 'center',
    fontFamily: fontFamily.UbuntuRegular,
    fontSize: 16,
    lineHeight: 18,
    color: white,
    paddingRight: hp(4),
  },
  cartContainer: {
    backgroundColor: '#11163A',
    height: hp(3.44),
    width: wp(7.47),
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 1,
    shadowColor: gray,
  },
  ticketContainer: {
    height: hp(3.44),
    width: wp(23.73),
    justifyContent: 'center',
    borderRadius: 5,
  },
  cart_ticketContainer: {
    // borderColor: white,
    // borderWidth: 1,
    justifyContent: 'space-around',
    flexDirection: 'row',
    marginTop: hp(1.7),
  },
  ticketLabel: {
    fontFamily: fontFamily.UbuntuRegular,
    fontSize: 18,
    lineHeight: 21,
    color: white,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
});
export default styles;
